### ISSUE TITLE
Show Community Samples

### ISSUE THREAD

**Issue by radeva** [NativeScript/marketplace-feedback#120] opened 2018-04-20 15:10 UTC
Show community created samples that are fed by the following repo https://github.com/NativeScript/code-samples

Includes showing samples with filter on top. 
Clicking on a sample, opens a playground link. 
Initially show just one screenshot.
Screenshots have fixed height of 1080px. Width may vary.

UX: https://ux.telerik.com/wireframes/NSPluginsMarketplace/#g=1&p=_n__marketplace_-_home_samples
Samples data: https://github.com/NativeScript/code-samples

**Comment by VladimirAmiorkov** [comment] 2018-04-25 06:48
AC:
- In preview the TS icon should be replaced with Vue
- "Frameworks" + "Categories" filters should work together
- Clicking "Sample Preview" should open link in new tab for the specific "Framework" filter
- All data from (https://github.com/NativeScript/code-samples/blob/master/categories/all.json) should be visible in the "Samples" section
- Screenshot should be the first one from the "screenshots" of the all.json
- Screenshot should be with height 345px (in marketplace) and should be the same height
- Screenshot width may vary
- Clicking "Submit your sample" should lead to github contributing guide (https://github.com/NativeScript/code-samples/blob/master/CONTRIBUTING.md)
- "Frameworks" filter should be single selection
- "Categories" filter should be single selection
- Default selection of "Frameworks" should be "Angular" and for "Categories" should be "All"
- The author may very between "Frameworks"

**Comment by DimitarTodorov** [comment] 2018-05-17 11:26
- Scrolls are shown on low resolutions over categories and frameworks labels.
https://www.screencast.com/t/RxQ7ZLG7. 
 --Will be fixed later. Not blocking for the release.
- ~Categories values and samples categories values are not aligned. Filtration by category is not working.~
- ~Screenshot preview of "Build a good looking login form" sample is broken
https://www.screencast.com/t/R2kxhwKODZnM~
- On mobile device(both Android/iOS) and on small resolution on desktop, the 'framework' and 'categories' labels are not positioned well. The font became bigger and they are overlapping. https://www.screencast.com/t/7mXE6BGTyS
  -- will be fixed after release. The issue is not blocking for the release.
- ~The "Build a good looking login form" broken screenshot, breaks the UI on low resolutions (mobile devices also) https://www.screencast.com/t/ZrwXRvrza~
- ~Missing code samples:~
  - ~"Building Custom Modal Dialogs"~
  - ~"Adding Dialogs to Your App"~
  - ~"Implementing Phone- and Tablet-specific Styling"~
  - ~"Implementing Split-View Components"~
  - ~"Using Multiple ListView Templates"~

- Some samples are not easy to find because there is no 'All' option for frameworks, like the 'All' option in categories. 
-- Will be discussed and decided later. It is OK to release the feature the behaviour is expected.

All AC are met.

**Closed as completed** 2018-05-23 08:33 UTC
Labels: feature
